on:
  push:
    branches:
      - '**' 
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore project dependencies
        run: dotnet restore './Assembly-CSharp.csproj'

      - name: Verify code formatting
        run: dotnet format './Assembly-CSharp.csproj' --verify-no-changes --verbosity diag

      - name: Fail if formatting or style checks fail
        if: failure()
        run: |
          echo "::error::Formatting or style checks failed. Please fix them before pushing."