name: Run Unity Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v4.3.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
            projectPath: ./
            githubToken: ${{ secrets.GITHUB_TOKEN }}
